### ISSUE TITLE
Diferença deste repo pro kickstart?

### ISSUE THREAD

**Issue by tonylampada** [dragoncss/dragoncss#1]
Hey Anderson, blz? 
Qual exatamente a diferença dos objetivos deste repositório e do seu outro https://github.com/Anderson-Juhasc/kickstart ?
Escreve no readme aih :-)

**Comment by Anderson-Juhasc** [comment]
O dragoncss estou escrevendo as classes com a metodologia BEM( http://bem.info/method/ ). E estou separando os modulos em repositorios diferentes para facilitar a manutenção.

Acabei fazendo o dragoncss com submodulos( mas encontrei alguns problemas qdo o dragoncss está dentro de outro .git ), mas pretendo migrar para o bower. Só preciso encontrar um pouco mais de tempo.

Abraço.

**Comment by Anderson-Juhasc** [comment]
O kickstart eu pretendo para-lo no momento. Quando eu atualizar o projeto dragoncss vou documentar melhor. ;)

**Comment by tonylampada** [comment]
Massa, vlw!
